"""AddShareLinkColumns

Revision ID: 3f7abbd34603
Revises: 
Create Date: 2026-02-27 10:06:41.727211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7abbd34603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_document_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('whiteboard_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_collaborative', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_share_link_room_id', ['room_id'])
        batch_op.create_foreign_key('fk_share_link_whiteboard_id', 'whiteboard', ['whiteboard_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_share_link_table_document_id', 'table_document', ['table_document_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_link', schema=None) as batch_op:
        batch_op.drop_constraint('fk_share_link_table_document_id', type_='foreignkey')
        batch_op.drop_constraint('fk_share_link_whiteboard_id', type_='foreignkey')
        batch_op.drop_constraint('uq_share_link_room_id', type_='unique')
        batch_op.drop_column('is_collaborative')
        batch_op.drop_column('room_id')
        batch_op.drop_column('whiteboard_id')
        batch_op.drop_column('table_document_id')

    # ### end Alembic commands ###
