"""Add knowledge_graph_id to share_link

Revision ID: bc514f5c4e64
Revises: adbb221a2d1a
Create Date: 2026-04-12 16:00:32.850860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc514f5c4e64'
down_revision = 'adbb221a2d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_graph_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('share_link_knowledge_graph_id_fkey', 'knowledge_graph', ['knowledge_graph_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_link', schema=None) as batch_op:
        batch_op.drop_constraint('share_link_knowledge_graph_id_fkey', type_='foreignkey')
        batch_op.drop_column('knowledge_graph_id')

    # ### end Alembic commands ###
